INTEGRATION_NAME = "Arcanna.ai"
AWAIT_ARCANNA_INFERENCE_SCRIPT_NAME = '{} - Await Inference'.format(INTEGRATION_NAME)
GET_JOBS_SCRIPT_NAME = '{} - Get Jobs'.format(INTEGRATION_NAME)
PING_SCRIPT_NAME = '{} - Ping'.format(INTEGRATION_NAME)
SEND_ARCANNA_ANALYST_FEEDBACK_SCRIPT_NAME = '{} - Send Analyst Feedback'.format(INTEGRATION_NAME)
SEND_CASE_SCRIPT_NAME = '{} - Send case'.format(INTEGRATION_NAME)
GET_CASE_RESPONSE_SCRIPT_NAME = '{} - Get case response'.format(INTEGRATION_NAME)
